version: "2"
output:
  formats: 
    json:
      path: golangci-lint-report.json
    checkstyle:
      path: checkstyle-golangci-lint-report.xml
linters:
  enable:
    - errcheck
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - govet
    - ineffassign
    - staticcheck
    - unused