// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gessnerfl/terraform-provider-instana/instana/restapi (interfaces: AlertingChannelResource)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	restapi "github.com/gessnerfl/terraform-provider-instana/instana/restapi"
	gomock "github.com/golang/mock/gomock"
)

// MockAlertingChannelResource is a mock of AlertingChannelResource interface
type MockAlertingChannelResource struct {
	ctrl     *gomock.Controller
	recorder *MockAlertingChannelResourceMockRecorder
}

// MockAlertingChannelResourceMockRecorder is the mock recorder for MockAlertingChannelResource
type MockAlertingChannelResourceMockRecorder struct {
	mock *MockAlertingChannelResource
}

// NewMockAlertingChannelResource creates a new mock instance
func NewMockAlertingChannelResource(ctrl *gomock.Controller) *MockAlertingChannelResource {
	mock := &MockAlertingChannelResource{ctrl: ctrl}
	mock.recorder = &MockAlertingChannelResourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockAlertingChannelResource) EXPECT() *MockAlertingChannelResourceMockRecorder {
	return m.recorder
}

// Delete mocks base method
func (m *MockAlertingChannelResource) Delete(arg0 restapi.AlertingChannel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockAlertingChannelResourceMockRecorder) Delete(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAlertingChannelResource)(nil).Delete), arg0)
}

// DeleteByID mocks base method
func (m *MockAlertingChannelResource) DeleteByID(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID
func (mr *MockAlertingChannelResourceMockRecorder) DeleteByID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockAlertingChannelResource)(nil).DeleteByID), arg0)
}

// GetOne mocks base method
func (m *MockAlertingChannelResource) GetOne(arg0 string) (restapi.AlertingChannel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOne", arg0)
	ret0, _ := ret[0].(restapi.AlertingChannel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOne indicates an expected call of GetOne
func (mr *MockAlertingChannelResourceMockRecorder) GetOne(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOne", reflect.TypeOf((*MockAlertingChannelResource)(nil).GetOne), arg0)
}

// Upsert mocks base method
func (m *MockAlertingChannelResource) Upsert(arg0 restapi.AlertingChannel) (restapi.AlertingChannel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", arg0)
	ret0, _ := ret[0].(restapi.AlertingChannel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upsert indicates an expected call of Upsert
func (mr *MockAlertingChannelResourceMockRecorder) Upsert(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockAlertingChannelResource)(nil).Upsert), arg0)
}
