// Code generated by MockGen. DO NOT EDIT.
// Source: instana/restapi/Instana-api.go

// Package mocks is a generated GoMock package.
package mocks

import (
	restapi "github.com/gessnerfl/terraform-provider-instana/instana/restapi"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockInstanaAPI is a mock of InstanaAPI interface
type MockInstanaAPI struct {
	ctrl     *gomock.Controller
	recorder *MockInstanaAPIMockRecorder
}

// MockInstanaAPIMockRecorder is the mock recorder for MockInstanaAPI
type MockInstanaAPIMockRecorder struct {
	mock *MockInstanaAPI
}

// NewMockInstanaAPI creates a new mock instance
func NewMockInstanaAPI(ctrl *gomock.Controller) *MockInstanaAPI {
	mock := &MockInstanaAPI{ctrl: ctrl}
	mock.recorder = &MockInstanaAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockInstanaAPI) EXPECT() *MockInstanaAPIMockRecorder {
	return m.recorder
}

// CustomEventSpecifications mocks base method
func (m *MockInstanaAPI) CustomEventSpecifications() restapi.RestResource {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CustomEventSpecifications")
	ret0, _ := ret[0].(restapi.RestResource)
	return ret0
}

// CustomEventSpecifications indicates an expected call of CustomEventSpecifications
func (mr *MockInstanaAPIMockRecorder) CustomEventSpecifications() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CustomEventSpecifications", reflect.TypeOf((*MockInstanaAPI)(nil).CustomEventSpecifications))
}

// UserRoles mocks base method
func (m *MockInstanaAPI) UserRoles() restapi.RestResource {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserRoles")
	ret0, _ := ret[0].(restapi.RestResource)
	return ret0
}

// UserRoles indicates an expected call of UserRoles
func (mr *MockInstanaAPIMockRecorder) UserRoles() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserRoles", reflect.TypeOf((*MockInstanaAPI)(nil).UserRoles))
}

// ApplicationConfigs mocks base method
func (m *MockInstanaAPI) ApplicationConfigs() restapi.RestResource {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplicationConfigs")
	ret0, _ := ret[0].(restapi.RestResource)
	return ret0
}

// ApplicationConfigs indicates an expected call of ApplicationConfigs
func (mr *MockInstanaAPIMockRecorder) ApplicationConfigs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplicationConfigs", reflect.TypeOf((*MockInstanaAPI)(nil).ApplicationConfigs))
}

// ApplicationAlertConfigs mocks base method
func (m *MockInstanaAPI) ApplicationAlertConfigs() restapi.RestResource {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplicationAlertConfigs")
	ret0, _ := ret[0].(restapi.RestResource)
	return ret0
}

// ApplicationAlertConfigs indicates an expected call of ApplicationAlertConfigs
func (mr *MockInstanaAPIMockRecorder) ApplicationAlertConfigs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplicationAlertConfigs", reflect.TypeOf((*MockInstanaAPI)(nil).ApplicationAlertConfigs))
}

// AlertingChannels mocks base method
func (m *MockInstanaAPI) AlertingChannels() restapi.RestResource {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AlertingChannels")
	ret0, _ := ret[0].(restapi.RestResource)
	return ret0
}

// AlertingChannels indicates an expected call of AlertingChannels
func (mr *MockInstanaAPIMockRecorder) AlertingChannels() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AlertingChannels", reflect.TypeOf((*MockInstanaAPI)(nil).AlertingChannels))
}

// AlertingConfigurations mocks base method
func (m *MockInstanaAPI) AlertingConfigurations() restapi.RestResource {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AlertingConfigurations")
	ret0, _ := ret[0].(restapi.RestResource)
	return ret0
}

// AlertingConfigurations indicates an expected call of AlertingConfigurations
func (mr *MockInstanaAPIMockRecorder) AlertingConfigurations() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AlertingConfigurations", reflect.TypeOf((*MockInstanaAPI)(nil).AlertingConfigurations))
}
